spring:
  profiles:
    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ci.check-consulting.net:10000/auth/realms/staff-manager-collab
jwt:
  auth:
    converter:
      resource-id: staff-manager-client


